/*
 * This source file was generated by the Gradle 'init' task
 */
package org.cli;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertDoesNotThrow(() -> classUnderTest.getGreeting(), "app should have a greeting");
    }
}
