/*
 * This source file was generated by the Gradle 'init' task
 */
package org.antlr;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import java.io.IOException;
import java.nio.file.Paths;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.antlr.v4.runtime.tree.*;

import org.antlr.BailLexer; // ignore the lsp error
import org.antlr.BailParser; // ignore the lsp error

public class AntlrTest {
	private void tryParse(CharStream input) throws ParseCancellationException {
		BailLexer bailLexer = new BailLexer(input);
		CommonTokenStream tokens = new CommonTokenStream(bailLexer);
		BailParser parser = new BailParser(tokens);
		parser.alloyFile();
	}

	@Test
	public void parseAll() throws Exception {
		CharStream input = CharStreams.fromPath(Paths.get("src/test/resources/antlr/catalyst/model-sets/2021-05-06-10-28-11-watform/AddressBook_nancy.als"));
		assertDoesNotThrow(()->this.tryParse(input), "Parse failed");
	}
}

